Feature/make tests optional
mantrajs/mantra-cli pull request #112
Opened 2017-02-07 17:23 UTC by macrozone

fixes https://github.com/mantrajs/mantra-cli/issues/111

2017-02-09 08:38 UTC, sungwoncho requested changes

2017-02-09 08:38 UTC, sungwoncho commented on lib/generators/component.js
> +  if(config.generateComponentTests) {
not sure if the conditional is needed. I think we should always delete everything related to the component when removing.

2017-02-09 08:38 UTC, sungwoncho commented on lib/generators/container.js
> +  if(config.generateContainerTests) {
please see https://github.com/mantrajs/mantra-cli/pull/112/files#r100253160

2017-02-09 08:39 UTC, sungwoncho commented
left a comment. open to suggestions.

2017-02-09 10:09 UTC, macrozone commented on lib/generators/component.js
> +  if(config.generateComponentTests) {
Was not sure about this. I thought, well if someone disabled test-creation and added some tests as well, that would be none of our business ;-)

but after second thought, you are right. I will remove that condition

2017-02-09 10:16 UTC, macrozone commented
@sungwoncho ok changed it!

2017-02-10 06:46 UTC, sungwoncho commented
It seems that test is failing. See https://travis-ci.org/mantrajs/mantra-cli/jobs/199922989#L2937-L2956. Maybe something broke in this branch.

2017-02-21 14:38 UTC, macrozone commented
ok thx, will take a look

2017-02-23 14:33 UTC, macrozone commented
@sungwoncho can you take a look?

2017-02-23 21:27 UTC, sungwoncho commented
I'll look and merge this weekend

2017-02-23 21:28 UTC, sungwoncho commented
LGTM. You can merge and publish. Don't forget to update https://github.com/mantrajs/mantra-cli/blob/master/RELEASE_NOTE.md. Thanks for your work.

2017-02-24 09:40 UTC, macrozone commented
I will do the release, but i can't merge here ;-)

2017-02-24 09:41 UTC, sungwoncho approved these changes

2017-02-24 09:43 UTC, macrozone commented
ok release is done, but i can't add a release tag here

2017-02-24 09:43 UTC, sungwoncho commented
@macrozone I thought we were both admins to this repo. Could you check https://github.com/mantrajs/mantra-cli/invitations?

2017-02-24 22:40 UTC, merged

2017-02-24 22:42 UTC, sungwoncho commented
Merged and tagged the release.

Thanks for your hard work. Please check your admin invitation.